name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html

    - name: Run tests with pytest
      run: |
        mkdir -p reports
        pytest --html=reports/report.html || true

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/report.html
